// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type ErrorResponse = {
    error: {
        code?: string;
        message?: string;
        details?: Array<string>;
    };
};

export type RegisterRequest = {
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    role: 'ADMIN' | 'TEACHER';
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type AuthResponse = {
    access_token: string;
    token_type: string;
    user: UserResponse;
};

export type UserResponse = {
    id: number;
    email: string;
    first_name: string;
    last_name: string;
    role: 'ADMIN' | 'TEACHER';
    status: 'ACTIVE' | 'BLOCKED';
    created_at: string;
};

export type TeacherCreateRequest = {
    email: string;
    first_name: string;
    last_name: string;
};

export type TeacherUpdateRequest = {
    first_name?: string;
    last_name?: string;
    status?: 'ACTIVE' | 'BLOCKED';
};

export type CourseCreateRequest = {
    title: string;
    description?: string;
    teacher_id: number;
    is_active: boolean;
};

export type CourseUpdateRequest = {
    title?: string;
    description?: string;
    is_active?: boolean;
};

export type CourseResponse = {
    id: number;
    title: string;
    description?: string | null;
    teacher_id: number;
    created_at: string;
    is_active: boolean;
};

export type GroupCreateRequest = {
    name: string;
    semester: string;
    year: number;
    course_id: number;
};

export type GroupUpdateRequest = {
    name?: string;
    semester?: string;
    year?: number;
};

export type GroupResponse = {
    id: number;
    name: string;
    semester: string;
    year: number;
    course_id: number;
    created_at: string;
};

export type StudentCreateRequest = {
    full_name: string;
    email?: string | null;
    group_id: number;
};

export type StudentUpdateRequest = {
    full_name?: string;
    email?: string | null;
    group_id?: number;
};

export type StudentResponse = {
    id: number;
    full_name: string;
    email?: string | null;
    group_id: number;
    created_at: string;
};

export type AssignmentCreateRequest = {
    title: string;
    description: string;
    language: string;
    deadline?: string | null;
    max_score: number;
    reference_solution?: string | null;
    course_id: number;
};

export type AssignmentUpdateRequest = {
    title?: string;
    description?: string;
    language?: string;
    deadline?: string | null;
    max_score?: number;
    reference_solution?: string | null;
};

export type AssignmentResponse = {
    id: number;
    title: string;
    description: string;
    language: string;
    deadline?: string | null;
    max_score: number;
    reference_solution?: string | null;
    course_id: number;
    created_at: string;
};

export type SubmissionCreateRequest = {
    assignment_id: number;
    student_id: number;
    file_path: string;
};

export type SubmissionResponse = {
    id: number;
    assignment_id: number;
    student_id: number;
    file_path: string;
    submitted_at: string;
    status: 'UPLOADED' | 'CHECKING' | 'DONE' | 'ERROR';
    plagiarism_score?: number | null;
};

export type SubmissionDetailsResponse = SubmissionResponse & {
    test_results?: Array<TestResultResponse>;
    comments?: Array<CommentResponse>;
    grade?: GradeResponse | null;
};

export type TestResultResponse = {
    id: number;
    test_case_id: number;
    passed: boolean;
    execution_time_ms?: number | null;
    error_message?: string | null;
};

export type TestResultListResponse = {
    items: Array<TestResultResponse>;
};

export type CommentCreateRequest = {
    content: string;
    line_number?: number | null;
    is_system_generated: boolean;
};

export type CommentResponse = {
    id: number;
    submission_id: number;
    author_id: number;
    content: string;
    line_number?: number | null;
    is_system_generated: boolean;
    created_at: string;
};

export type CommentListResponse = {
    items: Array<CommentResponse>;
};

export type GradeUpsertRequest = {
    score: number;
    max_score: number;
    is_published: boolean;
};

export type GradeResponse = {
    id: number;
    submission_id: number;
    score: number;
    max_score: number;
    graded_by: number;
    graded_at: string;
    is_published: boolean;
};

export type PlagiarismReportResponse = {
    submission_id: number;
    compared_with_id: number;
    similarity_percent: number;
    detected_blocks?: string;
    created_at: string;
};

export type JournalItemResponse = {
    student_id: number;
    student_name: string;
    submission_id?: number | null;
    status?: string | null;
    score?: number | null;
    max_score?: number | null;
    is_published?: boolean | null;
};

export type JournalResponse = {
    items: Array<JournalItemResponse>;
    page: number;
    size: number;
    total: number;
};

export type AdminStatisticsResponse = {
    active_courses: number;
    teachers_count: number;
    students_count: number;
    submissions_count: number;
    average_score: number;
};

export type AsyncTaskResponse = {
    message: string;
    status: string;
};

export type PaginationMeta = {
    page: number;
    size: number;
    total: number;
};

export type TeacherListResponse = {
    items: Array<UserResponse>;
    meta: PaginationMeta;
};

export type CourseListResponse = {
    items: Array<CourseResponse>;
    meta: PaginationMeta;
};

export type GroupListResponse = {
    items: Array<GroupResponse>;
    meta: PaginationMeta;
};

export type StudentListResponse = {
    items: Array<StudentResponse>;
    meta: PaginationMeta;
};

export type AssignmentListResponse = {
    items: Array<AssignmentResponse>;
    meta: PaginationMeta;
};

export type SubmissionListResponse = {
    items: Array<SubmissionResponse>;
    meta: PaginationMeta;
};

/**
 * Page number
 */
export type PageParam = number;

/**
 * Page size
 */
export type SizeParam = number;

export type TeacherIdParam = number;

export type CourseIdParam = number;

export type GroupIdParam = number;

export type StudentIdParam = number;

export type AssignmentIdParam = number;

export type SubmissionIdParam = number;

export type PostAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Invalid request data
     */
    400: ErrorResponse;
    /**
     * User with this email already exists
     */
    409: ErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * User registered successfully
     */
    201: AuthResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Требуется аутентификация или недействительный токен
     */
    401: ErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetTeachersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        status?: 'ACTIVE' | 'BLOCKED';
        /**
         * Поиск по имени, фамилии или электронной почте
         */
        search?: string;
    };
    url: '/teachers';
};

export type GetTeachersErrors = {
    /**
     * Требуется аутентификация или недействительный токен
     */
    401: ErrorResponse;
    /**
     * Недостаточно прав
     */
    403: ErrorResponse;
};

export type GetTeachersError = GetTeachersErrors[keyof GetTeachersErrors];

export type GetTeachersResponses = {
    /**
     * Список преподавателей
     */
    200: TeacherListResponse;
};

export type GetTeachersResponse = GetTeachersResponses[keyof GetTeachersResponses];

export type PostTeachersData = {
    body: TeacherCreateRequest;
    path?: never;
    query?: never;
    url: '/teachers';
};

export type PostTeachersErrors = {
    /**
     * Invalid request data
     */
    400: ErrorResponse;
    /**
     * Email уже существует
     */
    409: ErrorResponse;
};

export type PostTeachersError = PostTeachersErrors[keyof PostTeachersErrors];

export type PostTeachersResponses = {
    /**
     * Преподаватель создан
     */
    201: UserResponse;
};

export type PostTeachersResponse = PostTeachersResponses[keyof PostTeachersResponses];

export type DeleteTeachersByTeacherIdData = {
    body?: never;
    path: {
        teacherId: number;
    };
    query?: never;
    url: '/teachers/{teacherId}';
};

export type DeleteTeachersByTeacherIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type DeleteTeachersByTeacherIdError = DeleteTeachersByTeacherIdErrors[keyof DeleteTeachersByTeacherIdErrors];

export type DeleteTeachersByTeacherIdResponses = {
    /**
     * Преподаватель заблокирован
     */
    204: void;
};

export type DeleteTeachersByTeacherIdResponse = DeleteTeachersByTeacherIdResponses[keyof DeleteTeachersByTeacherIdResponses];

export type GetTeachersByTeacherIdData = {
    body?: never;
    path: {
        teacherId: number;
    };
    query?: never;
    url: '/teachers/{teacherId}';
};

export type GetTeachersByTeacherIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetTeachersByTeacherIdError = GetTeachersByTeacherIdErrors[keyof GetTeachersByTeacherIdErrors];

export type GetTeachersByTeacherIdResponses = {
    /**
     * Данные преподавателя
     */
    200: UserResponse;
};

export type GetTeachersByTeacherIdResponse = GetTeachersByTeacherIdResponses[keyof GetTeachersByTeacherIdResponses];

export type PutTeachersByTeacherIdData = {
    body: TeacherUpdateRequest;
    path: {
        teacherId: number;
    };
    query?: never;
    url: '/teachers/{teacherId}';
};

export type PutTeachersByTeacherIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type PutTeachersByTeacherIdError = PutTeachersByTeacherIdErrors[keyof PutTeachersByTeacherIdErrors];

export type PutTeachersByTeacherIdResponses = {
    /**
     * Преподаватель обновлен
     */
    200: UserResponse;
};

export type PutTeachersByTeacherIdResponse = PutTeachersByTeacherIdResponses[keyof PutTeachersByTeacherIdResponses];

export type GetCoursesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        teacher_id?: number;
        is_active?: boolean;
        search?: string;
    };
    url: '/courses';
};

export type GetCoursesResponses = {
    /**
     * Список курсов
     */
    200: CourseListResponse;
};

export type GetCoursesResponse = GetCoursesResponses[keyof GetCoursesResponses];

export type PostCoursesData = {
    body: CourseCreateRequest;
    path?: never;
    query?: never;
    url: '/courses';
};

export type PostCoursesErrors = {
    /**
     * Invalid request data
     */
    400: ErrorResponse;
};

export type PostCoursesError = PostCoursesErrors[keyof PostCoursesErrors];

export type PostCoursesResponses = {
    /**
     * Курс создан
     */
    201: CourseResponse;
};

export type PostCoursesResponse = PostCoursesResponses[keyof PostCoursesResponses];

export type DeleteCoursesByCourseIdData = {
    body?: never;
    path: {
        courseId: number;
    };
    query?: never;
    url: '/courses/{courseId}';
};

export type DeleteCoursesByCourseIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type DeleteCoursesByCourseIdError = DeleteCoursesByCourseIdErrors[keyof DeleteCoursesByCourseIdErrors];

export type DeleteCoursesByCourseIdResponses = {
    /**
     * Курс деактивирован
     */
    204: void;
};

export type DeleteCoursesByCourseIdResponse = DeleteCoursesByCourseIdResponses[keyof DeleteCoursesByCourseIdResponses];

export type GetCoursesByCourseIdData = {
    body?: never;
    path: {
        courseId: number;
    };
    query?: never;
    url: '/courses/{courseId}';
};

export type GetCoursesByCourseIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetCoursesByCourseIdError = GetCoursesByCourseIdErrors[keyof GetCoursesByCourseIdErrors];

export type GetCoursesByCourseIdResponses = {
    /**
     * Данные курса
     */
    200: CourseResponse;
};

export type GetCoursesByCourseIdResponse = GetCoursesByCourseIdResponses[keyof GetCoursesByCourseIdResponses];

export type PutCoursesByCourseIdData = {
    body: CourseUpdateRequest;
    path: {
        courseId: number;
    };
    query?: never;
    url: '/courses/{courseId}';
};

export type PutCoursesByCourseIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type PutCoursesByCourseIdError = PutCoursesByCourseIdErrors[keyof PutCoursesByCourseIdErrors];

export type PutCoursesByCourseIdResponses = {
    /**
     * Курс обновлен
     */
    200: CourseResponse;
};

export type PutCoursesByCourseIdResponse = PutCoursesByCourseIdResponses[keyof PutCoursesByCourseIdResponses];

export type GetGroupsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        course_id?: number;
        year?: number;
        semester?: string;
    };
    url: '/groups';
};

export type GetGroupsResponses = {
    /**
     * Groups list
     */
    200: GroupListResponse;
};

export type GetGroupsResponse = GetGroupsResponses[keyof GetGroupsResponses];

export type PostGroupsData = {
    body: GroupCreateRequest;
    path?: never;
    query?: never;
    url: '/groups';
};

export type PostGroupsResponses = {
    /**
     * Группа создана
     */
    201: GroupResponse;
};

export type PostGroupsResponse = PostGroupsResponses[keyof PostGroupsResponses];

export type DeleteGroupsByGroupIdData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type DeleteGroupsByGroupIdResponses = {
    /**
     * Группа удалена
     */
    204: void;
};

export type DeleteGroupsByGroupIdResponse = DeleteGroupsByGroupIdResponses[keyof DeleteGroupsByGroupIdResponses];

export type GetGroupsByGroupIdData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type GetGroupsByGroupIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetGroupsByGroupIdError = GetGroupsByGroupIdErrors[keyof GetGroupsByGroupIdErrors];

export type GetGroupsByGroupIdResponses = {
    /**
     * Данные группы
     */
    200: GroupResponse;
};

export type GetGroupsByGroupIdResponse = GetGroupsByGroupIdResponses[keyof GetGroupsByGroupIdResponses];

export type PutGroupsByGroupIdData = {
    body: GroupUpdateRequest;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type PutGroupsByGroupIdResponses = {
    /**
     * Группа обновлена
     */
    200: GroupResponse;
};

export type PutGroupsByGroupIdResponse = PutGroupsByGroupIdResponses[keyof PutGroupsByGroupIdResponses];

export type GetStudentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        group_id?: number;
        search?: string;
    };
    url: '/students';
};

export type GetStudentsResponses = {
    /**
     * Список студентов
     */
    200: StudentListResponse;
};

export type GetStudentsResponse = GetStudentsResponses[keyof GetStudentsResponses];

export type PostStudentsData = {
    body: StudentCreateRequest;
    path?: never;
    query?: never;
    url: '/students';
};

export type PostStudentsResponses = {
    /**
     * Студент создан
     */
    201: StudentResponse;
};

export type PostStudentsResponse = PostStudentsResponses[keyof PostStudentsResponses];

export type DeleteStudentsByStudentIdData = {
    body?: never;
    path: {
        studentId: number;
    };
    query?: never;
    url: '/students/{studentId}';
};

export type DeleteStudentsByStudentIdResponses = {
    /**
     * Студент удален
     */
    204: void;
};

export type DeleteStudentsByStudentIdResponse = DeleteStudentsByStudentIdResponses[keyof DeleteStudentsByStudentIdResponses];

export type GetStudentsByStudentIdData = {
    body?: never;
    path: {
        studentId: number;
    };
    query?: never;
    url: '/students/{studentId}';
};

export type GetStudentsByStudentIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetStudentsByStudentIdError = GetStudentsByStudentIdErrors[keyof GetStudentsByStudentIdErrors];

export type GetStudentsByStudentIdResponses = {
    /**
     * Данные студента
     */
    200: StudentResponse;
};

export type GetStudentsByStudentIdResponse = GetStudentsByStudentIdResponses[keyof GetStudentsByStudentIdResponses];

export type PutStudentsByStudentIdData = {
    body: StudentUpdateRequest;
    path: {
        studentId: number;
    };
    query?: never;
    url: '/students/{studentId}';
};

export type PutStudentsByStudentIdResponses = {
    /**
     * Студент обновлен
     */
    200: StudentResponse;
};

export type PutStudentsByStudentIdResponse = PutStudentsByStudentIdResponses[keyof PutStudentsByStudentIdResponses];

export type GetAssignmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        course_id?: number;
        language?: string;
        deadline_from?: string;
        deadline_to?: string;
    };
    url: '/assignments';
};

export type GetAssignmentsResponses = {
    /**
     * Список заданий
     */
    200: AssignmentListResponse;
};

export type GetAssignmentsResponse = GetAssignmentsResponses[keyof GetAssignmentsResponses];

export type PostAssignmentsData = {
    body: AssignmentCreateRequest;
    path?: never;
    query?: never;
    url: '/assignments';
};

export type PostAssignmentsResponses = {
    /**
     * Задание создано
     */
    201: AssignmentResponse;
};

export type PostAssignmentsResponse = PostAssignmentsResponses[keyof PostAssignmentsResponses];

export type DeleteAssignmentsByAssignmentIdData = {
    body?: never;
    path: {
        assignmentId: number;
    };
    query?: never;
    url: '/assignments/{assignmentId}';
};

export type DeleteAssignmentsByAssignmentIdResponses = {
    /**
     * Задание удалено
     */
    204: void;
};

export type DeleteAssignmentsByAssignmentIdResponse = DeleteAssignmentsByAssignmentIdResponses[keyof DeleteAssignmentsByAssignmentIdResponses];

export type GetAssignmentsByAssignmentIdData = {
    body?: never;
    path: {
        assignmentId: number;
    };
    query?: never;
    url: '/assignments/{assignmentId}';
};

export type GetAssignmentsByAssignmentIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetAssignmentsByAssignmentIdError = GetAssignmentsByAssignmentIdErrors[keyof GetAssignmentsByAssignmentIdErrors];

export type GetAssignmentsByAssignmentIdResponses = {
    /**
     * Данные задания
     */
    200: AssignmentResponse;
};

export type GetAssignmentsByAssignmentIdResponse = GetAssignmentsByAssignmentIdResponses[keyof GetAssignmentsByAssignmentIdResponses];

export type PutAssignmentsByAssignmentIdData = {
    body: AssignmentUpdateRequest;
    path: {
        assignmentId: number;
    };
    query?: never;
    url: '/assignments/{assignmentId}';
};

export type PutAssignmentsByAssignmentIdResponses = {
    /**
     * Задание обновлено
     */
    200: AssignmentResponse;
};

export type PutAssignmentsByAssignmentIdResponse = PutAssignmentsByAssignmentIdResponses[keyof PutAssignmentsByAssignmentIdResponses];

export type GetSubmissionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        assignment_id?: number;
        student_id?: number;
        status?: 'UPLOADED' | 'CHECKING' | 'DONE' | 'ERROR';
    };
    url: '/submissions';
};

export type GetSubmissionsResponses = {
    /**
     * Список отправок
     */
    200: SubmissionListResponse;
};

export type GetSubmissionsResponse = GetSubmissionsResponses[keyof GetSubmissionsResponses];

export type PostSubmissionsData = {
    body: SubmissionCreateRequest;
    path?: never;
    query?: never;
    url: '/submissions';
};

export type PostSubmissionsErrors = {
    /**
     * Invalid request data
     */
    400: ErrorResponse;
};

export type PostSubmissionsError = PostSubmissionsErrors[keyof PostSubmissionsErrors];

export type PostSubmissionsResponses = {
    /**
     * Отправка создана
     */
    201: SubmissionResponse;
};

export type PostSubmissionsResponse = PostSubmissionsResponses[keyof PostSubmissionsResponses];

export type GetSubmissionsBySubmissionIdData = {
    body?: never;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}';
};

export type GetSubmissionsBySubmissionIdErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetSubmissionsBySubmissionIdError = GetSubmissionsBySubmissionIdErrors[keyof GetSubmissionsBySubmissionIdErrors];

export type GetSubmissionsBySubmissionIdResponses = {
    /**
     * Данные отправки
     */
    200: SubmissionDetailsResponse;
};

export type GetSubmissionsBySubmissionIdResponse = GetSubmissionsBySubmissionIdResponses[keyof GetSubmissionsBySubmissionIdResponses];

export type PostSubmissionsBySubmissionIdCheckData = {
    body?: never;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}/check';
};

export type PostSubmissionsBySubmissionIdCheckErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type PostSubmissionsBySubmissionIdCheckError = PostSubmissionsBySubmissionIdCheckErrors[keyof PostSubmissionsBySubmissionIdCheckErrors];

export type PostSubmissionsBySubmissionIdCheckResponses = {
    /**
     * Проверка отправки начата
     */
    202: AsyncTaskResponse;
};

export type PostSubmissionsBySubmissionIdCheckResponse = PostSubmissionsBySubmissionIdCheckResponses[keyof PostSubmissionsBySubmissionIdCheckResponses];

export type GetSubmissionsBySubmissionIdCommentsData = {
    body?: never;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}/comments';
};

export type GetSubmissionsBySubmissionIdCommentsResponses = {
    /**
     * Список комментариев
     */
    200: CommentListResponse;
};

export type GetSubmissionsBySubmissionIdCommentsResponse = GetSubmissionsBySubmissionIdCommentsResponses[keyof GetSubmissionsBySubmissionIdCommentsResponses];

export type PostSubmissionsBySubmissionIdCommentsData = {
    body: CommentCreateRequest;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}/comments';
};

export type PostSubmissionsBySubmissionIdCommentsResponses = {
    /**
     * Комментарий создан
     */
    201: CommentResponse;
};

export type PostSubmissionsBySubmissionIdCommentsResponse = PostSubmissionsBySubmissionIdCommentsResponses[keyof PostSubmissionsBySubmissionIdCommentsResponses];

export type PutSubmissionsBySubmissionIdGradeData = {
    body: GradeUpsertRequest;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}/grade';
};

export type PutSubmissionsBySubmissionIdGradeErrors = {
    /**
     * Invalid request data
     */
    400: ErrorResponse;
};

export type PutSubmissionsBySubmissionIdGradeError = PutSubmissionsBySubmissionIdGradeErrors[keyof PutSubmissionsBySubmissionIdGradeErrors];

export type PutSubmissionsBySubmissionIdGradeResponses = {
    /**
     * Оценка сохранена
     */
    200: GradeResponse;
};

export type PutSubmissionsBySubmissionIdGradeResponse = PutSubmissionsBySubmissionIdGradeResponses[keyof PutSubmissionsBySubmissionIdGradeResponses];

export type GetAssignmentsByAssignmentIdJournalData = {
    body?: never;
    path: {
        assignmentId: number;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        status?: 'UPLOADED' | 'CHECKING' | 'DONE' | 'ERROR';
    };
    url: '/assignments/{assignmentId}/journal';
};

export type GetAssignmentsByAssignmentIdJournalResponses = {
    /**
     * Журнал оценок
     */
    200: JournalResponse;
};

export type GetAssignmentsByAssignmentIdJournalResponse = GetAssignmentsByAssignmentIdJournalResponses[keyof GetAssignmentsByAssignmentIdJournalResponses];

export type GetSubmissionsBySubmissionIdPlagiarismData = {
    body?: never;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}/plagiarism';
};

export type GetSubmissionsBySubmissionIdPlagiarismErrors = {
    /**
     * Ресурс не найден
     */
    404: ErrorResponse;
};

export type GetSubmissionsBySubmissionIdPlagiarismError = GetSubmissionsBySubmissionIdPlagiarismErrors[keyof GetSubmissionsBySubmissionIdPlagiarismErrors];

export type GetSubmissionsBySubmissionIdPlagiarismResponses = {
    /**
     * Отчет о плагиате
     */
    200: PlagiarismReportResponse;
};

export type GetSubmissionsBySubmissionIdPlagiarismResponse = GetSubmissionsBySubmissionIdPlagiarismResponses[keyof GetSubmissionsBySubmissionIdPlagiarismResponses];

export type GetSubmissionsBySubmissionIdTestResultsData = {
    body?: never;
    path: {
        submissionId: number;
    };
    query?: never;
    url: '/submissions/{submissionId}/test-results';
};

export type GetSubmissionsBySubmissionIdTestResultsResponses = {
    /**
     * Результаты тестов
     */
    200: TestResultListResponse;
};

export type GetSubmissionsBySubmissionIdTestResultsResponse = GetSubmissionsBySubmissionIdTestResultsResponses[keyof GetSubmissionsBySubmissionIdTestResultsResponses];

export type GetAdminStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/statistics';
};

export type GetAdminStatisticsErrors = {
    /**
     * Недостаточно прав
     */
    403: ErrorResponse;
};

export type GetAdminStatisticsError = GetAdminStatisticsErrors[keyof GetAdminStatisticsErrors];

export type GetAdminStatisticsResponses = {
    /**
     * Системная статистика
     */
    200: AdminStatisticsResponse;
};

export type GetAdminStatisticsResponse = GetAdminStatisticsResponses[keyof GetAdminStatisticsResponses];
